### ISSUE TITLE
communication: Where and how to discuss things?

### ISSUE THREAD

**Issue by NitkarshChourasia** [bra1nDump/ai-task-vscode#6]
If somebody wants to connect with you. Discuss something, how would someone do it?!
It would be good if you opened a discussion tab on this repository.
Because I think, Issues are good for issues only.
What are your thoughts on it?!

**Comment by bra1nDump** [comment]
Great idea, we have a discord server https://discord.gg/pAgk26Fm, I think its better for discussions compared to discussions on github itself

**Comment by NitkarshChourasia** [comment]
> Great idea, we have a discord server https://discord.gg/pAgk26Fm, I think its better for discussions compared to discussions on github itself

Great.
